; for this to be used on the program, 
;either edit the code directly (on meg_f.py specifically) or 
;rename this file to 'meg_stg.ini'

; NOTE!!
;> it's case-insensitive, which means 
;upper or lower case doesn't affect the values 
;(it does affect the variable name still though, so never change that one!)

[DEFAULT]
maxnum = 99
;maxnum is an abbreviation for maximum number
; it is the maximum or the limit range when
;generating the number.
; appropriate value: any integer
; DEFAULT : 99
islocal = True
; for now it can only be True, as online
;savings are not currently available.
;nor is it a priority anyways:P but a plan.. maybe?
; THE value can only be True, so it is preferred to not set it to anything else.
enable_timer = True
; if you don't like to have a timer, you can disable it
;but that also means that it'll not be eligible
;to be saved on the record log
; appropriate value: True/False
; DEFAULT : True
decimal_digits = 2
; the amount of digits behind the decimal point
; appropriate value: any integer
; DEFAULT : 2
record_display = 0
; Here's the appropriate value
; appropriate value: 0-2 (that's a range)
; 0 means ALWAYS ASK, 1 means to show in markdown format, 
;2 is the normal display (set in the main file aka `meg.py`)
; DEFAULT : 0 (always ask)